# Nav
social:
  Github: https://github.com/FrontendSophie
  LinkedIn: https://www.linkedin.com/in/frontendsophie/

# Background image, color
background: 'url(https://cdn.jsdelivr.net/gh/frontendsophie/hexo-theme-autumn@1.0.0/source/img/button-bg.png) #f3f3f3'

# Favicon
favicon: https://cdn.jsdelivr.net/gh/frontendsophie/hexo-theme-autumn@1.0.0/source/img/favicon.ico

# SEO
keywords: 'hexo, autumn'

# Widgets, enable at least one
widgets:
  category: enabled
  archive: enabled
  tag: enabled

# Set the first image in post to cover
auto_cover: true
